POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "email": "saut@wiscaksono.com",
    "username": "sautmanurang",
    "password": "Saut123123123"
}



POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "saut@wiscaksono.com",
    "password": "Saut123123123"
}

