POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "email": "admin@wiscaksono.com",
    "username": "wiscaksono",
    "password": "Wisnuajjh123"
}

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "admin@wiscaksono.com",
    "password": "Wisnuajjh123"
}

