GET {{BASE_URL}}/todo
Authorization: Bearer {{TOKEN}}

POST {{BASE_URL}}/todo
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "title": "TODO 1",
    "completed": true
}


GET {{BASE_URL}}/todo/b365a3f5-998a-4e71-b684-2e2d1ab3bc83
Authorization: Bearer {{TOKEN}}

DELETE {{BASE_URL}}/todo/788a4ee6-0c3b-4bd4-b095-2f34989f98fb
Authorization: Bearer {{TOKEN}}

PUT {{BASE_URL}}/todo/b365a3f5-998a-4e71-b684-2e2d1ab3bc83
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "title": "KONTOL",
    "completed": false
}


DELETE {{BASE_URL}}/todo/all
Authorization: Bearer {{TOKEN}}
