GET {{BASE_URL}}/user
Authorization: Bearer {{TOKEN}}

GET {{BASE_URL}}/user/f62ae8ce-0888-4ce4-a887-41c7fbf2c360
Authorization: Bearer {{TOKEN}}

DELETE {{BASE_URL}}/user/0f87659f-167d-4239-a6a8-35caf37b5d36
Authorization: Bearer {{TOKEN}}
