GET {{BASE_URL}}/user
Authorization: Bearer {{TOKEN}}

GET {{BASE_URL}}/user/b130eb5d-2474-484e-9900-2b58095bbc36
Authorization: Bearer {{TOKEN}}

DELETE {{BASE_URL}}/user/24f465c2-943a-4c6a-a860-4b5a1fb5901e
Authorization: Bearer {{TOKEN}}
