package config

var (
	APP_PORT   = GetENV("APP_PORT")
	APP_SECRET = GetENV("APP_SECRET")

	DB_USER     = GetENV("DB_USER")
	DB_PASSWORD = GetENV("DB_PASSWORD")
	DB_NAME     = GetENV("DB_NAME")

	PGADMIN_EMAIL    = GetENV("PGADMIN_EMAIL")
	PGADMIN_PASSWORD = GetENV("PGADMIN_PASSWORD")
)
